import type { SlotPorts } from "./slot.js";

/** The storage image the appliance compose file pins; verify uses the same digest. */
export function storageImageFrom(composeYaml: string): string {
  const image = /image:\s*(rustfs\/rustfs@sha256:[0-9a-f]{64})/.exec(composeYaml)?.[1];
  if (image === undefined) throw new Error("docker-compose.yml no longer pins rustfs/rustfs by digest; update tools/verify/render.ts");
  return image;
}

export interface StorageCredentials {
  accessKey: string;
  secretKey: string;
}

/**
 * A compose project of its own per slot. Volumes are declared without a `name:`
 * so Docker names them `<project>_pgdata`; the owner's `routiq_pgdata` can never
 * be one of them. Ports bind to loopback only.
 */
export function renderCompose(project: string, ports: SlotPorts, storageImage: string, storage: StorageCredentials): string {
  return `# Generated by pnpm verify up. Do not edit; pnpm verify down removes it.
name: ${project}

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: routiq
      POSTGRES_PASSWORD: routiq
      POSTGRES_DB: routiq_dev
    ports:
      - "127.0.0.1:${ports.postgres}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U routiq -d routiq_dev"]
      interval: 2s
      timeout: 3s
      retries: 30

  storage:
    image: ${storageImage}
    environment:
      RUSTFS_ACCESS_KEY: ${storage.accessKey}
      RUSTFS_SECRET_KEY: ${storage.secretKey}
      RUSTFS_CORS_ALLOWED_ORIGINS: "*"
    ports:
      - "127.0.0.1:${ports.storage}:9000"
    volumes:
      - storagedata:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/health/live"]
      interval: 2s
      timeout: 3s
      retries: 30

volumes:
  pgdata: {}
  storagedata: {}
`;
}

/**
 * The repo's vite config hardcodes port 5173 and a proxy to :3001. This wrapper
 * spreads it and points both at the slot, with a cache dir of its own so two
 * slots and the owner's dev server never share optimized deps.
 */
export function renderViteConfig(baseConfigPath: string, webRoot: string, cacheDir: string, ports: SlotPorts): string {
  return `// Generated by pnpm verify up. Do not edit; pnpm verify down removes it.
import base from ${JSON.stringify(baseConfigPath)};

export default {
  ...base,
  root: ${JSON.stringify(webRoot)},
  cacheDir: ${JSON.stringify(cacheDir)},
  clearScreen: false,
  server: {
    ...base.server,
    host: "127.0.0.1",
    port: ${ports.web},
    strictPort: true,
    hmr: { port: ${ports.web} },
    proxy: { "/v1": "http://127.0.0.1:${ports.api}" },
  },
};
`;
}
