import type { categories } from "../db/schema.js";

export function presetCategories(
  workspaceId: string,
): Array<typeof categories.$inferInsert> {
  return [
    {
      workspaceId,
      kind: "ASSET_CLASS",
      code: "TRUCK",
      active: true,
      labelFr: "Camion",
      labelEn: "Truck",
    },
    {
      workspaceId,
      kind: "ASSET_CLASS",
      code: "TRAILER",
      active: true,
      labelFr: "Remorque",
      labelEn: "Trailer",
    },
    {
      workspaceId,
      kind: "ASSET_CLASS",
      code: "BUS",
      active: true,
      labelFr: "Bus",
      labelEn: "Bus",
    },
    {
      workspaceId,
      kind: "ASSET_CLASS",
      code: "VAN",
      active: true,
      labelFr: "Fourgonnette",
      labelEn: "Van",
    },
    {
      workspaceId,
      kind: "DOCUMENT_TYPE",
      code: "INSURANCE",
      active: true,
      labelFr: "Assurance",
      labelEn: "Insurance",
    },
    {
      workspaceId,
      kind: "DOCUMENT_TYPE",
      code: "PERMIT",
      active: true,
      labelFr: "Permis",
      labelEn: "Permit",
    },
    {
      workspaceId,
      kind: "EXPENSE_CATEGORY",
      code: "FUEL",
      active: true,
      labelFr: "Carburant",
      labelEn: "Fuel",
      profitabilityLayer: "DIRECT",
      evidencePolicy: "RECEIPT_EXPECTED",
    },
    {
      workspaceId,
      kind: "EXPENSE_CATEGORY",
      code: "REPAIRS",
      active: true,
      labelFr: "Réparations",
      labelEn: "Repairs",
      profitabilityLayer: "MAINTENANCE",
      evidencePolicy: "RECEIPT_EXPECTED",
    },
    {
      workspaceId,
      kind: "EXPENSE_CATEGORY",
      code: "INSURANCE",
      active: true,
      labelFr: "Assurance",
      labelEn: "Insurance",
      profitabilityLayer: "OWNERSHIP",
      evidencePolicy: "RECEIPT_EXPECTED",
    },
    {
      workspaceId,
      kind: "EXPENSE_CATEGORY",
      code: "PARKING",
      active: true,
      labelFr: "Stationnement",
      labelEn: "Parking",
      profitabilityLayer: "DIRECT",
      evidencePolicy: "NO_RECEIPT_EXPECTED",
    },
    {
      workspaceId,
      kind: "EXPENSE_CATEGORY",
      code: "LOADING",
      active: true,
      labelFr: "Chargement",
      labelEn: "Loading",
      profitabilityLayer: "DIRECT",
      evidencePolicy: "NO_RECEIPT_EXPECTED",
    },
    {
      workspaceId,
      kind: "REVENUE_CATEGORY",
      code: "FREIGHT_REVENUE",
      active: true,
      labelFr: "Recettes de fret",
      labelEn: "Freight revenue",
      profitabilityLayer: "DIRECT",
      evidencePolicy: "RECEIPT_EXPECTED",
    },
    {
      workspaceId,
      kind: "REVENUE_CATEGORY",
      code: "TICKET_REVENUE",
      active: true,
      labelFr: "Recettes de billetterie",
      labelEn: "Ticket revenue",
      profitabilityLayer: "DIRECT",
      evidencePolicy: "RECEIPT_EXPECTED",
    },
  ];
}
